RedHatInsights/ocp-advisor-frontend

.travis.yml

While it looks like you setup your Travis key correctly (but since I don't have admin on this repo I can't verify that) you forgot to edit your `.travis.yml`.

fix(travis): deploy

---

README.md

Saw it while reading, must correct 😂

Small pointless commit for a typo

---

src/Components/ClusterHeader/ClusterHeader.js
src/Services/AccountManagementService.js
src/Services/SmartProxy.js
src/Store/index.js

Clusters can have custom names set up by administrators. AMS API is the place where Advisor can obtain this data.

Show cluster display name

---

config/setupTests.js
jest.config.js
package.json
src/Components/Breadcrumbs/Breadcrumbs.js
src/Components/Breadcrumbs/Breadcrumbs.test.js
src/Components/Breadcrumbs/index.js
src/Components/Cluster/Cluster.js
src/Components/Cluster/Cluster.test.js
src/Components/Cluster/__snapshots__/Cluster.test.js.snap
src/Components/Cluster/index.js
src/Components/ClusterHeader/ClusterHeader.js
src/Components/ClusterHeader/ClusterHeader.test.js
src/Components/ClusterHeader/__snapshots__/ClusterHeader.test.js.snap
src/Components/ClusterHeader/index.js
src/Routes.js
src/Services/SmartProxy.js

Fixes https://issues.redhat.com/browse/CCXDEV-5407

Create basic unit tests

---

src/Components/ClusterRules/ClusterRules.js

Added some OUIA ids to cluster recommendations view

OUIA-enablement

---

ARCHITECTURE.md
package-lock.json
package.json
src/Components/Recommendation/Recommendation.js
src/Components/Recommendation/RuleDetails.js
src/Services/SmartProxy.js
src/Utilities/Api.js

Fixes https://issues.redhat.com/browse/CCXDEV-6311.
- Renders  "Is this recommendation helpful?" message with voting actions.

Enable recommendation voting

---

compiled-lang/en.json
src/App.scss
src/Components/MessageState/EmptyStates.js
src/Messages.js
src/Routes.js

Fixes https://issues.redhat.com/browse/CCXDEV-6573.

Added coming soon error message to the Clusters pages in OCP Advisor

---

cypress/fixtures/ClustersListTable/data.json
package-lock.json
package.json
src/AppConstants.js
src/Components/ClustersList/index.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/ClustersListTable/index.js
src/Components/Common/Tables.js
src/Components/RecsListTable/RecsListTable.js
src/Routes.js
src/Services/Filters.js
src/Services/SmartProxy.js

Fixes https://issues.redhat.com/browse/CCXDEV-6312

Add systems (clusters) page

---

src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.scss
src/Components/RecsListTable/RecsListTable.spec.ct.js
src/Services/Filters.js

Recommendations list page: minor enhancements

---

cypress/fixtures/AffectedClustersTable/data.json
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Services/Filters.js

Single recommendation page improvements

---

cypress.json
package.json
src/Components/ClusterHeader/ClusterHeader.js
src/Components/ClusterHeader/ClusterHeader.spec.ct.js
src/Components/ClusterHeader/index.js
src/Utilities/Loaders.js

Render the last seen timestamp on the single cluster page

---

src/Components/ClustersListTable/ClustersListTable.js
src/Components/RecsListTable/RecsListTable.js

Added isStickyHeader to the Table component

Added missing props to the Table Component

---

package-lock.json
package.json
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/Breadcrumbs/index.js
src/Components/Cluster/Cluster.spec.ct.js
src/Components/ClusterHeader/ClusterHeader.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/Modals/DisableRule.js
src/Components/Recommendation/Recommendation.js
src/Components/RecsListTable/RecsListTable.js

Bump @patternfly/react-* versions; enhance OUIA support

---

cypress/fixtures/ClustersListTable/data.json
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js

Solving the issue with an empty string in cluster.last_checked_at

Fixing the N/A is not sortable in the Clusters page

---

cypress/fixtures/api/insights-results-aggregator/v1/clusters/41c30565-b4c9-49f2-a4ce-3277ad22b258/report.json
src/Components/ClusterRules/ClusterRules.spec.ct.js

Wrote the test that checks the "first" query parameter
Edited the report.json that contains mock data according to the new standard

First query parameter cypress test

---

config/dev.webpack.config.js
cypress/fixtures/Cluster/report.json
src/Components/Cluster/Cluster.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Wrote 2 tests that check the additional query parameters for the Recs list page 
Added fixtures to the tests for single Cluster page
Created new tests to test the query parameters
Improved previous tests we had for the single Cluster page

Query parameters Tests

---

config/dev.webpack.config.js
src/Components/AffectedClustersTable/AffectedClustersTable.js

With this update, we can use the command
`npm run start:beta` to launch stage dev env

Updating dev env to stage

---

src/App.scss

Showed this to the Maria Doruskova and she "approved" of these changes
Old version - bigger padding on a left side
New version - smaller padding on both sides

Added a custom padding to the recs table

---

cypress/utils/components.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

Set of tests for bulk selector.
Probably these test go beyond the scope of the definition of the bulk selector that we do in the code, thus limiting the scope of these tests is open for discussion.

Tests for bulk selector in affected clusters table

---

src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/Common/Tables.js

Fixed a filtering bug on the Clusters List Table
Wrote tests to check the bugfix

Fixed a filtering bug on the Clusters List Table

---

src/Components/Common/Tables.js
src/Services/SmartProxy.js

Added a check for the clusters that missing both cluster name and external id

Cluster List added a check for the clusters that missing both clustername and external id

---

.travis.yml
README.md
package-lock.json
package.json

This integrates `semantic-release` with Advisor and adds automatic versioning. 
Commit messages should from now on comply with the Angular commit message conventions: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines so that a new release can be triggered with each merge to the **master** branch. Types of commits are listed here: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type and should be all supported with the configuration introduced by this PR.

feat: integrate semantic-release

---

config/dev.webpack.config.js
cypress/utils/components.js
src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-7189.
- Makes the recommendations list table remove the name filter textual input after the name chip is removed or all the filters are reset.

Clear Name filter textual input after chip is removed  

---

src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-7192

fix(ClusterRules): fix description chip category name

---

src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

According to the task CCXDEV-7614 I updated the "Reset filters" behavior

fix(RecsListTable): Reset filters button behavior update

---

src/Components/ClustersListTable/ClustersListTable.js

According to task 7615 updated the reset filters behavior

fix(ClusterListTable): Updated the reset filters behavior

---

cypress/fixtures/ClusterRules/data.json
src/AppConstants.js
src/Components/Cluster/Cluster.js
src/Components/Cluster/Cluster.spec.ct.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/Loading/Loading.js

* FIX: If a user opens the cluster rules page with the "first" search parameter (== the value of the parameter dictates which rule to show first in the table) and tries to sort by any columns, the table will not react and not sort the reports.
* REFACTOR: remove the part of the table logic from `Cluster` component.

Cluster reports table: refactor and fix the bug with inability to sort the table

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Services/Filters.js

Set default sorting to last seen
Updated 1 failing test

fix(AffectedClustersTable): set default sorting to last seen

---

src/App.js
src/AppEntry.js

jira: https://issues.redhat.com/browse/RHCLOUD-18732

Use application basename to react to APP_NAVIGATION event

---

cypress/support/commands.js
cypress/utils/components.js
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

This PR mainly affects table related test suites.
The goal is to try to reduce common code and nest tests into meaningful categories.
Create a new method to get ouia components by type and rename the one for IDs
Add new components to the global file
Set some common table related utilities

Refactor test 

---

cypress/utils/pagination.js
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js

- Move itemsPerPage function to a utils module
- Move pagination util functions to pagination module

Pagination utils

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Used the MR to also add some comments for other improvements in the future

Pagination related tests for RecsListTable

---

cypress/support/commands.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

Remove duplicated tests and move missing check to the remaining ones.
Allow cypress OUIA commands to receive element tags as optional parameters

Remove duplicated tests

---

cypress/support/index.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/Breadcrumbs/Breadcrumbs.spec.ct.js
src/Components/Cluster/Cluster.spec.ct.js
src/Components/ClusterHeader/ClusterHeader.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/Modals/DisableRule.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

This way it will be autoimported in all test files
Nice finding @gkarat , thank you!

Move importing PF CSS to cypress support

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js

- rename data and set default sorting for ease testing
- improve test checking cluster names show names instead of uuids
- improve test checking cluster names are hyperlinks. Test also improved in ClustersListTable tests

Affected clusters tests improvement

---

cypress/utils/components.js
cypress/utils/filters.js
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

- use utils functions
- remove hardcoded values
- improve default tests: pagination, sorting and filtering

RecsListTable tests improvement

---

src/Components/ClustersListTable/ClustersListTable.spec.ct.js

Improve Clusters list table tests

---

src/Components/Cluster/index.js
src/Components/ClustersList/index.js
src/Components/Recommendation/index.js
src/Components/RecsList/index.js

Fixes https://issues.redhat.com/browse/CCXDEV-7449

refactor: use updateDocumentTitle to update page titles

---

cypress/utils/components.js
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

- Add expect URL for ClustersListTable default sorting
- Created function to verify table sorting
- Reduce ROOT usage and use TABLE component
- [ClustersListTable] rename props and data variables
- Removed old hack (CCXDEV-7192)
- Use column name instaed of index

Minor improvements to tests

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Use expect assertions as they do not retry if fail

Change data tests to use expect assertion

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

Use the same criteria for the filters in AffectedClusterTable: use filtersConf and filtering utilities

Use filtersConf approach in Affected clusters table

---

cypress/utils/filters.js
cypress/views/filterableTable.js
package-lock.json
src/Components/RecsListTable/RecsListTable.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-8128.

Avoid force: true in cypress tests

---

src/Components/Modals/ViewHostAcks.js
src/Components/Recommendation/Recommendation.js

- host ack modal enable button
- recommendation page card for disabled hosts

[CCXDEV-8325] Adding OUIA  IDs

---

src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

- Check disabling multiple clusters button is also modified
- Test for test of selector

[CCXDEV-7133] Bulk selector tests improve

---

src/Components/ClusterRules/ClusterRules.spec.ct.js

Check row counts in ClusterRules

[CCXDEV-7133] Improve default tests

---

src/Components/AffectedClustersTable/AffectedClustersTable.js

Fixes https://issues.redhat.com/browse/CCXDEV-8350.

fix(Recommendation clusters): Fix always checked checkbox in the disable rule modal

---

src/Components/ClustersList/index.js
src/Components/RecsList/index.js

Fixes https://issues.redhat.com/browse/CCXDEV-8331.

refactor(Page headers): use PF Title instead FEC PageHeaderTitle

---

cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/MessageState/MessageState.js

Fixes https://issues.redhat.com/browse/CCXDEV-8329.

refactor(Empty states): set proper OUIA attributes to empty state containers

---

cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

- Create a function for filtering tests that wraps shared code
- Use function in single filter tests
- Use function in combined filter tests
[CCXDEV-8215](https://issues.redhat.com/browse/CCXDEV-8215)

Share code for filtering tests

---

src/Components/RecsListTable/RecsListTable.spec.ct.js

Improve test for disable label in recommendations list by checking it is present in all expected rows
[CCXDEV-7414](https://issues.redhat.com/browse/CCXDEV-7414)

Disabled label

---

src/Components/Recommendation/Recommendation.spec.ct.js

- Add test for category labels
- Set base for other test of single recommendation page. Follow up https://issues.redhat.com/browse/CCXDEV-8415
[CCXDEV-6982](https://issues.redhat.com/browse/CCXDEV-6982)

[CCXDEV-6982] Check category labels in recommendation page

---

cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Refactor sorting tests creating a common function that encloses the functionality
[CCXDEV-8215](https://issues.redhat.com/browse/CCXDEV-8215)

Function for sorting tests

---

src/Components/Recommendation/Recommendation.spec.ct.js

- Check actions button to ack/deack recommendation
- Check acked recommendation label
- Check acked recommendation actions button triggers deacj
- Check acked recommendation info card
- Check acked recommendation does not show clusters table

Improve single recommendation tests

---

compiled-lang/en.json
src/Messages.js

This fixes the missing message on the vote click on the recommendation details page.

fix(Recommendation page): fix missing thank you message on vote click

---

config/dev.webpack.config.js
cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
src/AppConstants.js
src/Components/ClusterRules/ClusterRules.cy.js
src/Components/ClusterRules/ClusterRules.js

Added the impacted column component + state when the impacted data is not available + tests

feat(ClusterRules): Add impacted to single Cluster page

---

cypress/utils/components.js
cypress/utils/filters.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/RecsListTable/RecsListTable.cy.js

Added new tests for the ClusterList table
I had to add 2 checks to separate how urlParamConvert and hasChip work.
I think that this could be improved

feat(ClustersList): new tests for url params

---

src/Components/Recommendation/Recommendation.cy.js

Test for checking that justification messages are correctly displayed (if they should)
Fixes [CCXDEV-9144](https://issues.redhat.com/browse/CCXDEV-9144)

Test for justification message when rule is acked

---

build_deploy.sh
package.json
pr_check.sh

Implements https://issues.redhat.com/browse/OCPADVISOR-25 and follows https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_step_3_add_build_and_pr_check_scripts.

Ephemeral environments: add build and PR check scripts

---

.github/workflows/cypress.yml
.travis.yml

Tested it on my fork and it works :)

feat(GitHubActions): Add cypress yml config to run github actions

---

deploy/frontend.yml

This patch adds the frontend resource YAML for the new frontend build process.

Add frontend resource yaml

---

package-lock.json
package.json

https://issues.redhat.com/browse/ADVISOR-2945

chore(deps):updating advisor component

---

README.md
config/dev.webpack.config.js
package-lock.json
package.json
profiles/local-frontend-and-api.js
profiles/local-frontend.js
src/AppEntry.js
src/Components/ClusterHeader/ClusterHeader.js

To test, you can run via `/beta` or `/preview`. We previously had issues with the local app being served. To ensure that it is properly being served, run the app via beta and make a change in the code or add a console log and ensure that you're getting local changes.

chore(RHIF-220): Update /beta to /preview

---

src/Components/UpgradeRisksTable/ClusterOperatorsList.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.cy.js

Fixes https://issues.redhat.com/browse/OCPADVISOR-87.

fix(OCPADVISOR-87): Don't map cluster operator conditions

---

src/App.js
src/AppEntry.js

jira: https://issues.redhat.com/browse/RHCLOUD-27284

fix: Remove obsolete APP_NAVIGATION listener

---

src/Components/Workload/Workload.js
src/Components/Workload/index.js
src/Components/WorkloadsHeader/WorkloadsHeader.js
src/Components/WorkloadsHeader/index.js
src/Components/WorkloadsList/index.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Components/WorkloadsListTable/index.js
src/Routes.js

added basic routes
added folders
added rough component files

feat(ocpadvisor-121): folders routes and components

---

src/AppConstants.js
src/Components/Common/Tables.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Services/Filters.js

https://issues.redhat.com/browse/OCPADVISOR-123

feat(OCPADVISOR-123): filter configs filter slice and constants

---

cypress/fixtures/api/insights-results-aggregator/v2/workloads.json
src/App.scss
src/AppConstants.js
src/Components/ShieldSet.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Utilities/Workloads.js

New severity shields component

feat(OCPADVISOR-121): update severity label component

---

cypress/fixtures/api/insights-results-aggregator/v2/workloads.json
src/Components/WorkloadsListTable/WorkloadsListTable.js

How to check the PR
Make sure that the columns are sortable

feat(OCPADVISOR-128): workloads table sorting

---

cypress/fixtures/api/insights-results-aggregator/v2/workloads.json
src/Components/WorkloadsListTable/WorkloadsListTable.cy.js

PR for the initial setup of Cypress for the workloads table

feat(OCPADVISOR-121): initial setup for cypress tests

---

src/AppConstants.js
src/Components/Workload/Workload.js
src/Components/WorkloadRules/WorkloadRules.js

[OCPADVISOR-133](https://issues.redhat.com/browse/OCPADVISOR-133)
Basic workload recommendation table
Setup
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock)
2. `make build` (takes a few minutes for me, coffee time ☕)
2.1. can speed it up with `make build -j 4` to run multiple jobs at once
4. `make run`
5. Test the mocked api `curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo`
6. Run the app `MOCK=true npm run start:proxy:beta`
7. Workloads should load mocked data

feat(OCPADVISOR-133): workload recommendation table

---

src/AppConstants.js
src/Components/Common/Tables.js
src/Components/WorkloadsListTable/WorkloadsListTable.cy.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Services/Filters.js

Fixed the incorrect filter parameter
https://issues.redhat.com/browse/RHINENG-5523

fix(RHINENG-5523): fixed the incorrect filter parameter

---

package-lock.json
package.json
src/Components/ClusterRules/ClusterRules.js
src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
src/Components/WorkloadRules/WorkloadRules.js
src/Utilities/TemplateProcessor.js

https://issues.redhat.com/browse/OCPADVISOR-132
First prototype of the expanded details. 
Some of the data is missing from the API response and I had to "improvise" to add it
Also, according to the Shayna I don't need to reduce the width of the objects table in the expanded details.

feat(OCPADVISOR-132): workloads recommendations expanded details

---

config/prod.webpack.config.js

This fixes the build of preview and stable code

chore(webpack): introduce better check between preview and stable build

---

cypress/fixtures/api/insights-results-aggregator/objects.json
src/AppConstants.js
src/Components/Common/Tables.js
src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
src/Components/MessageState/EmptyStates.js
src/Components/ObjectsModal/ObjectsModal.js
src/Components/ObjectsModalTable/ObjectsModalTable.js
src/Components/ObjectsModalTable/ObjectsModalTable.test.js
src/Services/Filters.js
src/Utilities/Workloads.js

https://issues.redhat.com/browse/RHINENG-5527
Mocks
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/dgb4Lp2
Open workloads -> workloads details and then click "View all objects" button in the expanded details for any row
How to run it locally:
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock) or pull the latest changes
2. make build
3. can speed it up with make build -j 4 to run multiple jobs at once
4. make run
5. Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
6. Run the app MOCK=true npm run start:proxy:beta
7. Workloads should load mocked data
8. Review the PR

feat(RHINENG-5527): Objects Modal

---

src/Components/Common/Tables.js
src/Components/MessageState/EmptyStates.js
src/Components/WorkloadRules/WorkloadRules.js

I fixed the total risk filter so it should work with mock data
I added an empty state for 0 matching results

fix(workloads details): fixed a total risk filter + empty state

---

cypress/fixtures/api/insights-results-aggregator/v2/workload/00000001-0001-0001-0001-000000000005-fad82c1f-96db-430f-b3ec-503fb9eeb7bb/info.json
src/Components/WorkloadRules/WorkloadRules.js

The behavior of row expanded should be the same as in cluster details.
To test:
Try switching expanded rows on and off and apply filters. The expanded row should stay expanded if it is shown in the filtered results

feat(rhineng-8063): expanded row behavior and more mock data variety

---

cypress/utils/table.js
src/Components/WorkloadsListTable/WorkloadsListTable.cy.js

[OCPADVISOR-130](https://issues.redhat.com/browse/OCPADVISOR-130)

test(OCPADVISOR-130): Workloads table tests

---

src/Components/ShieldSet.js

fix(bug): fixing shieldset so it would like before r18 update

---

src/AppConstants.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

https://issues.redhat.com/browse/RHINENG-8334

chore(RHINENG-8334): hide severity column until backend is ready

---

src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
src/Components/ObjectsModal/ObjectsModal.js
src/Components/Workload/Workload.cy.js
src/Components/Workload/Workload.js
src/Components/Workload/index.js
src/Components/WorkloadHeader/index.js
src/Components/WorkloadRules/WorkloadRules.js
src/Components/WorkloadsListTable/index.js

Connecting real API to the UI
Removed mocked data
Added a conditional rendering to hide objects table and button when the objects are absent for the recommendation.
Passed more data to the Expanded Rules Details to render the data using template processor
Conditional rendering to hide the Note part of the Expanded Rules Details component. It is dependent on the existence of a namespace Name.

Connect real api

---

cypress/fixtures/api/insights-results-aggregator/objects.json
cypress/support/commands.js
cypress/utils/table.js
package-lock.json
package.json
src/Components/ObjectsModal/ObjectsModal.cy.js
src/Components/Workload/Workload.cy.js

https://issues.redhat.com/browse/RHINENG-5503

feat(RHINENG-5503): Objects modal cypress tests

---

src/Components/WorkloadRules/WorkloadRules.js

Now we're showing a different empty state on the 404 error. 
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/P1Wm4yQ

fix(RHINENG-5526): empty state for 404 error

---

src/Components/MessageState/EmptyStates.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

https://issues.redhat.com/browse/RHINENG-8462
Temporary link that will be used for the docs
https://redhat-internal.slack.com/archives/CLABA9CHY/p1709727002174119?thread_ts=1709718840.715419&cid=CLABA9CHY

feat(rhineng-5496): combined empty state for workloads table

---

src/Components/Workload/Workload.cy.js
src/Components/Workload/Workload.js
src/Components/WorkloadHeader/index.js

I missed the fact that we're making the API call twice, I removed the redundant one and passed the data from the parent component

fix(bug): remove redundant API call

---

src/Components/ObjectsModal/ObjectsModal.js

Filters for objects now refreshed on closing a modal
https://issues.redhat.com/browse/RHINENG-8808

feat(rhineng-8808): objects filter now refreshed on close

---

src/Components/MessageState/EmptyStates.js

https://issues.redhat.com/browse/RHINENG-8462

feat(RHINENG-8462): update empty state link with catalog redhat

---

src/Components/Workload/Workload.cy.js

The workload test describe message was not correct.

Update describe message in test

---

src/Components/Workload/Workload.cy.js

fixed workload details tests after pf update

fix(tests): fixed workload details tests after pf update

---

cypress.config.js
cypress/fixtures/api/insights-results-aggregator/v2/upgrade-risks-prediction.json
cypress/utils/interceptors.js
cypress/utils/table.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Services/SmartProxy.js

[RHINENG-8253](https://issues.redhat.com/browse/RHINENG-8253)

feat(RHINENG-8253): Update risk label in cluster page

---

cypress.config.js
package-lock.json
package.json

I found this https://docs.cypress.io/guides/references/experiments#Experimental-Flake-Detection-Features
In cypress docs and trying it

fix(tests): using experimental strategy to detect flaky tests

---

package-lock.json
package.json
src/Components/ClusterRules/ClusterRules.js

Because of this PR we have to update our UI
https://github.com/RedHatInsights/frontend-components/pull/1992
https://issues.redhat.com/browse/RHINENG-9046

fix(RHINENG-9046): updating report details after fec update

---

src/Components/Cluster/Cluster.cy.js
src/Components/ClusterHeader/ClusterHeader.js

https://issues.redhat.com/browse/RHINENG-9058
Before
After

fix(RHINENG-9058): fixed action button alignment

---

fec.config.js

We don't need this option, so I am removing it

update fec config

---

src/AppConstants.js
src/Components/Common/Tables.js
src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
src/Components/WorkloadRules/WorkloadsRules.test.js
src/Services/Filters.js
src/Utilities/Workloads.js

Added object names to the small table in expanded details
Added filter that allows to filter object by their name
Added URL param conversion for the object names
Added tests
https://issues.redhat.com/browse/RHINENG-11380

feat(RHINENG-11380): add object names to the expanded details and filter

---

src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js

Fixing bugs mentioned in these tickets
https://issues.redhat.com/browse/RHINENG-8850
https://issues.redhat.com/browse/RHINENG-11380

fix(RHINENG-11380): hotfix for the case when object names are absent

---

.travis.yml
babel.config.js
build_deploy.sh
package-lock.json
package.json
pr_check.sh

https://issues.redhat.com/browse/RHINENG-15368
- remove unused babel packages
- update babel config
- update pipelines to use Node v18
- remove unused variables in Travis config

chore(RHINENG-15368): Cleanup and consolidate frontend repositories

---

cypress/support/component.js
fec.config.js
src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ObjectsModalTable/ObjectsModalTable.js
src/Components/RecsListTable/RecsListTable.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

I am separating this PR into smaller pieces https://github.com/RedHatInsights/ocp-advisor-frontend/pull/898
1) this pr to update UI and some small fixes for the repository
2) update fec and cypress tests in next PR

chore(RHINENG-16145): update UI before fec update

---

package.json

https://issues.redhat.com/browse/RHINENG-17121

make jest ignore unnecessary files for coverage
