config/dev.webpack.config.js
config/prod.webpack.config.js
src/App.js
src/AppConstants.js
src/Components/Breadcrumbs/Breadcrumbs.js
src/Components/ClusterRules/ClusterRules.js
src/Components/RuleLabels/RuleLabels.js
src/Messages.js
src/Services/SmartProxy.js

Add category filter; fix typos; edit webpack config

---

compiled-lang/en.json
src/App.js
src/AppEntry.js
src/Messages.js

Fixes https://issues.redhat.com/browse/CCXDEV-6237.
Introduces authentication check and wrapper for Advisor. Once the user has authenticated within insights chroming, the content of Advisor is exposed. The redux store is also now not initialized, while the user has not passed auth check.

Wrap app with auth check

---

src/Components/Cluster/Cluster.js
src/Components/Cluster/Cluster.test.js
src/Components/Cluster/__snapshots__/Cluster.test.js.snap
src/Components/Cluster/index.js

Fixes https://issues.redhat.com/browse/CCXDEV-6390.
- Makes the single cluster page show the breadcrumb with information about the requested cluster.
- When a display name is available, show it instead of cluster id.

Always show header with breadcrumb for single cluster page

---

compiled-lang/en.json
config/cypress.webpack.config.js
src/Components/ClusterRules/ClusterRules.js
src/Messages.js
src/Services/AccountManagementService.js

- For the single cluster page, remove the bulk select and all select-related features from the recommendations table. (See screenshot 1)
- When deployed in pre-prod envs (e.g. qa/beta), use AMS API in the stage environment.
- Change empty state body message for the rules table (screenshot 2).

Remove select feature; utilize stage AMS API for pre-prod envs

---

src/Components/ClusterRules/ClusterRules.js

Fixes the toolbar for clusters that have recommendations hitting; however, all of them are disabled. 
Before:
After (the cluster is the same):

Enable filter toolbar for cluster with disabled recs

---

src/Components/RecsListTable/RecsListTable.js

Described status expanded true/false in the state using useState
used property expandAll of PrimaryToolbar to pass it function collapseAll

Added expand/collapse all button with icon to the Primary toolbar

---

cypress/fixtures/AffectedClustersTable/data.json
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersList/index.js
src/Components/Recommendation/index.js
src/Components/RecsList/index.js

Improve page document titles; affected clusters table enhancements

---

src/AppConstants.js
src/Components/Cluster/index.js
src/Components/ClusterRules/ClusterRules.js
src/Services/SmartProxy.js

Rewrote API query so we'll request only enabled rules for single cluster page
Removed unnecessary code related to the "status" of the rules on the single cluster page

Hide disabled rules for single cluster page

---

src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js

The first look when a user opens the page

Added collapse/expand all button to the single cluster page

---

src/Components/Recommendation/RuleDetails.js
src/Components/RecsListTable/RecsListTable.js
src/Utilities/intlHelper.js

Update params that are passed to the RuleDetails federated module

---

src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

There was a bug with filters
After debugging and discussing it with Georgy he advised to remove this line of code, it was a culprit causing this bug.
1. Navigate to the recommendations page
2. Open the filter "Cluster impacted" and leave the "1 or more" selected and then select the "None" (so both are selected)
3. Open the filter status and select "All"
The "1 or more" filter for "Cluster impacted" is removed from the list of filters.

Fixed a bug with the clusters Impacted filter and status All

---

src/Components/Labels/CategoryLabel.js
src/Components/RecsListTable/RecsListTable.js

Added props isCompact to the labels in Recommendations List Table
To update the label total risk in the expanded rule we need to create a separate patch for the rhel advisor
Asked Martin about <InsightsLabel /> props and he told me that there is a bug so currently, we need to pass rest={{ isCompact: true }} instead isCompact="true" to get the result we need.

Compact Labels in Recommendations Table

---

compiled-lang/en.json
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/MessageState/EmptyStates.js
src/Messages.js

New empty state for the Clusters table that will be rendered when the clusters.length === 0

Fix corner case when cluster list receive 0 clusters

---

src/Components/Recommendation/Recommendation.js

Fixed a bug with an API request for enabling rules from the single recommendation page

Single page recommendation bug fix

---

src/Components/Labels/RuleLabels.js
src/Components/Recommendation/Recommendation.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

The style for the label in the name column was missing the isCompact props

Fixed a style in the recommendation table name column and single recommendation page

---

src/AppConstants.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/Common/Tables.js
src/Components/Labels/CategoryLabel.js
src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js
src/Services/Filters.js

If the page is requested with the additional search (query) parameters (e.g., `?limit=20&offset=0&total_risk=1,2`), then apply the filters in the table.
This enables usage of `total_risk`, `category`, `likelihood`, `impact`, `text` and other parameters to be added to the URL as search query parameters. Once added, the table will pre-fill the appropriate filters.
This enables usage of `total_risk`, `category`, `text` and other parameters to be added to the URL as search query parameters. Once added, the table will pre-fill the appropriate filters.
This enables usage of the `first` parameter to be added to the URL as a search query parameter. Once added with the valid rule ID, it will try to find the rule from the list of affecting recommendations and show it as the first item.
Examples:
- …

Synchronize table filters, offset and limit with URL query parameters (1/2)

---

src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.js
src/Components/Common/Tables.js

The patch enables the usage of the "first" query parameter with the rule id as a valid value. If given, the list will show the requested rule as the first in hitting recommendations for this cluster.

Cluster recs: support "first" query parameter

---

src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

1)Fixed sorting in the affected clusters table on the single recommendation page.
2)Wrote test to check the sorting behaviour.
3)The tests show that it is up to our expectations (see the screenshots)
First click that causes sorting
Second click that causes sorting

Affected clusters table sorting update

---

src/Components/Cluster/Cluster.js
src/Components/Cluster/Cluster.spec.ct.js
src/Components/Cluster/index.js
src/Components/ClusterHeader/ClusterHeader.js
src/Components/ClusterHeader/ClusterHeader.spec.ct.js
src/Components/ClusterHeader/index.js
src/Services/AccountManagementService.js
src/Services/SmartProxy.js

Added a query to the smart proxy file that should get the display name for the cluster
attached it to the components
removed the unnecessary AMS query

Fixed the single cluster page header display name

---

src/Components/Modals/ViewHostAcks.js

The variable containing cluster_name was updated and required this change
Before
After

Fixed the cluster name in the modal

---

src/Components/ClusterRules/ClusterRules.js

Added a ternary operator to check if the cluster has rule hits
If the cluster has 0 rule hits filter in the primary toolbar will be disabled
Otherwise, the filter in the primary toolbar will work

Single cluster page disabled filter

---

src/Services/SmartProxy.js

Added a parameter to the clusters page endpoint and recommendation page endpoint
Added a parameter to all smart proxy endpoints to fetch data if the user lost his internet and then got it back
Link to the RTK docs https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#default-cache-behavior

Clusters list, recommendations list pages: solving the UI inconstistency

---

src/Components/ClusterRules/ClusterRules.js
src/Components/RuleDetailsLocal/RuleDetails.js

fix(labels): rule details component: make labels compact

---

src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-7407.
If a table is sorted and the sorted parameter is equal to some of the entities (for example, 3 rules with a Moderate total risk), their original order must be preserved in both ascending and descending sortings.

fix: keep original order of entities in all tables

---

src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js

The Reset filters button had the wrong name "Clear filters"
Had to update it and tests

fix(AffectedClustersTable): Reset filters button update

---

src/Components/Modals/DisableRule.js

This fixes a bug: if a user selects multiple clusters, unchecks the "Disable recommendation for selected clusters" flag, then the recommendation will only be disabled for selected clusters. This is incorrect, and the recommendation should be disabled for all clusters in this scenario.
Tests to be written in https://github.com/RedHatInsights/ocp-advisor-frontend/pull/111.

fix(disable modal): bug with multiple selections

---

src/Components/Cluster/index.js
src/Components/ClustersList/index.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/Recommendation/index.js
src/Components/RecsList/index.js
src/Components/RecsListTable/RecsListTable.js

Revert the time-based data refresh feature implemented in https://github.com/RedHatInsights/ocp-advisor-frontend/pull/177 since it breaks integration tests and requires a proper discussion.

fix(tables): revert the time-based refresh feature

---

cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js

- remove `last_checked_at` when empty for /clusters endpoint to match actual behavior
- remove duplicated sorting related tests in ClustersListTable

Last seen at

---

src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-7900.
Recording the opened rows for the single cluster page
Fixed the test
The expand collapse behavior:
1)When the user opens the page for the first time - the first row is expanded
2)If he clicks sort after that, only the rows that were expanded will stay that way
if he expands several different rows\all rows before that -> only these rows will stay expanded

fix(ClusterRules): Open rows memorization 

---

src/Components/Cluster/Cluster.spec.ct.js
src/Components/ClusterRules/ClusterRules.js

The bug was discovered when the cypress rows counting test was failing (for a manual test, the bug is not visible, however, automated tests are able to identify them since they manipulate with interface way faster than users). 
This makes the table show rows only when the data filtering and sorting are complete.

fix(Cluster rules table): display table rows only when filtering is completed

---

compiled-lang/en.json
cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
package-lock.json
package.json
src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/Common/Tables.js
src/Components/RecsListTable/RecsListTable.js
src/Messages.js
src/Services/Filters.js

The PR makes the single recommendation view render the **cluster version** column. The value is contained in the API response (`GET /clusters_detail`) within the `meta.cluster_version` path.
Mocked in https://marvelapp.com/prototype/g70a1he/screen/86034747.
Implements https://issues.redhat.com/browse/CCXDEV-6435.

Render cluster version in the affected clusters table

---

compiled-lang/en.json
cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
cypress/utils/filters.js
src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/Common/Tables.js
src/Messages.js
src/Services/Filters.js

The PR makes the clusters list view render the cluster version column. The value is contained in the API response (`GET /v2/clusters`) within the `cluster_version` path.
Mocked in https://marvelapp.com/prototype/g70a1he/screen/82818324.
Implements https://issues.redhat.com/browse/CCXDEV-7011.

Display cluster version in the clusters list table

---

compiled-lang/en.json
cypress/utils/components.js
cypress/utils/table.js
package-lock.json
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Components/Cluster/Cluster.js
src/Components/Cluster/Cluster.spec.ct.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/Loading/Loading.js
src/Components/MessageState/EmptyStates.js
src/Components/MessageState/MessageState.js
src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js
src/Messages.js

Implements https://issues.redhat.com/browse/CCXDEV-8280, https://issues.redhat.com/browse/CCXDEV-8242
Mainly refactors how table components are handling empty states. Also adds tests to check that the empty state titles, messages, and icons are rendered correctly.
Some illustrations:

Refactor empty state handling across tables; implement tests

---

cypress/utils/components.js
cypress/utils/table.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClusterRules/ClusterRules.spec.ct.js
src/Components/RecsListTable/RecsListTable.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-8191.
Moves the "arrow" button for expanding/hovering all rows from the toolbar to table headers.

Fix wrong placement of "Expand all" button in tables

---

src/Components/ClusterRules/ClusterRules.js

Fixes https://issues.redhat.com/browse/CCXDEV-8272.
The table, to update `filteredRows`, must look at the RTQ query data, not the state variable `reports`. The infinite re-render was triggered by the fact that even though previous and current states had `reports` equal to an empty array, from a JS perspective, they are perceived as different objects ([] === [] ~> false).

fix(Cluster reports): fix infinite table re-render when there are no rules

---

src/Components/ClustersListTable/ClustersListTable.spec.ct.js
src/Components/RecsListTable/RecsListTable.spec.ct.js

Fixes https://issues.redhat.com/browse/CCXDEV-8306.
I can't say for sure, but my gut says nesting all the checks within the `then` callback will let us prevent the tests from being flaky. I can't test it anyhow, but if we don't see the issue again in the future, this thing must probably have fixed that.

test(Pagination check): nest checkRowCounts within "then" callback

---

compiled-lang/en.json
cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
package-lock.json
src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
src/Messages.js

Implements https://issues.redhat.com/browse/CCXDEV-7462.
The "Impacted" column displays the date when the recommendation first hit the particular cluster. The column is sortable, no filter is required.

feat(Single recommendation page): add Impacted column

---

src/Components/Recommendation/Recommendation.js
src/Components/RecsListTable/RecsListTable.js

This removes trailing slashes from endpoints. Before, it was causing 301 responses.

refactor: remove trailing slashes in endpoint paths

---

README.md
package.json
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.cy.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/RecsListTable/RecsListTable.js

Implements https://issues.redhat.com/browse/OCPADVISOR-24.
Use the `data-ouia-safe` tag and `ouiaSafe` PF component property in each table in Advisor (recs list, clusters list, affected clusters list, cluster reports list). The tag is set to false if there is an animation in a table (= a table is in the loading state); otherwise is true.

OUIA safe tags for tables

---

src/Components/Modals/ViewHostAcks.js
src/Components/Modals/ViewHostsAcks.cy.js
src/Components/Recommendation/Recommendation.cy.js

Improve tests for recommendations page
* test modal for disabled hosts
* test page without disabled clusters
* test enabling all clusters from card
Implements [CCXDEV-8415](https://issues.redhat.com/browse/CCXDEV-8415)

Recommendation page tests

---

src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.cy.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/RecsListTable/RecsListTable.js

Fixes https://issues.redhat.com/browse/OCPADVISOR-47.
All tables were incorrectly setting the `data-ouia-safe` attribute to false when there is an error requesting API. Now, they should always be setting it to `true` in all scenarios when no animation and visual change is ongoing (as expected).

Fix the "OUIA data safe set to false for cluster without archives"

---

src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/RecsListTable/RecsListTable.js

This continues on https://issues.redhat.com/browse/OCPADVISOR-47: fixes the incorrect data-ouia-safe while tables are in the error empty state. Also, the PR rearranges `useEffect`s so that extra re-renders are avoided.

fix(Tables): reduce re-renders; fix the incorrect data-ouia-safe attribute

---

src/Components/RecsListTable/RecsListTable.cy.js

Improve the test checking the recommendations table content to check that the link for "View N affected clusters" is display.
It aims to check regression of https://github.com/RedHatInsights/ocp-advisor-frontend/issues/69
Fixes CCXDEV-9143

Test N affected clusters

---

compiled-lang/en.json
src/AppConstants.js
src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
src/Messages.js

The title of the "Impacted" column wasn't describing well what we're showing there. This PR replaces it with "First impacted".

chore(OCPADVISOR-52): replace impacted label

---

src/AppConstants.js

Just a small cosmetic change to make all tables align their columns so that they fit their content and don't have extra width.
Example from the affected clusters list:

feat(Tables): Align columns to fit their content

---

package-lock.json
package.json

Updating redux toolkit to fix the bug in stage
The bug - for some reason when you switch between recommendations and clusters page the table stop loading and get stuck in the "isFetching" 
to reproduce, open the https://console.stage.redhat.com/openshift/insights/advisor/recommendations
Go to Clusters table then back to Recommendations table
How to test this PR
0. You need both Insights Chrome and OCP Advisor locally.
1. Add route in Insights Chrome a to the wepback.config.js
`...proxy({
env: 'stage-beta',
port: 1337,
appUrl: [/^\/*$/, /^\/beta\/*$/],
useProxy: true,
publicPath,
proxyVerbose: true,
isChrome: true,
routes: {
'/apps/ocp-advisor': {
host: 'https://localhost:8004',
},
},
}),`
2. run insights chrome with "npm run dev"
3. run this command in OCP Advisor
"BETA=true npx webpack …

fix(redux):Fixing bug in stage

---

cypress/utils/components.js
cypress/utils/pagination.js
cypress/utils/table.js
src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClusterRules/ClusterRules.cy.js
src/Components/ClusterRules/ClusterRules.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/RecsListTable/RecsListTable.cy.js
src/Components/RecsListTable/RecsListTable.js
src/Services/Filters.js

When you click on "Reset filters" values set for pagination and sorting get also reset. This is on every table in the app.
This PR ensures that on "Reset filters" click, only filters get reset and not pagination or sorting.

[OCPADVISOR-6] Reset filters resets only filters

---

src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Services/Filters.js

On affected clusters and clusters list tables, if you change per page or reset/apply filters, you will stay on the same page. Pages should be reset to 1 if you change the per page count or apply or remove a filter. This PR fixes those issues.

[OCPADVISOR-62] Reset page number on filter

---

src/Components/Cluster/Cluster.js
src/Components/ClustersList/index.js
src/Components/Recommendation/Recommendation.js
src/Components/RecsList/index.js
src/Components/RecsListTable/RecsListTable.js

This removes the usage of Main component that was connecting to the global chroming store and was prone to errors. The replacement is the section tag with custom PF class names.

refactor: Replace Main with section tag

---

src/Components/RecsListTable/RecsListTable.cy.js
src/Components/RecsListTable/RecsListTable.js

Implements https://issues.redhat.com/browse/OCPADVISOR-66.
This adds a new section to expanded rule content on the recommendations list table. The section shows information about the risk of change for the given rule.
Navigate to /openshift/insights/advisor/recommendations. Check that for the rows that have risk of change value, the expanded information contains the risk of change section. For the rules that do not have (currently, all external rules have risk of change, but the tests cover this case), the section must be empty in the expanded content.

feat(Recs list): Risk of change details section

---

config/dev.webpack.config.js
config/prod.webpack.config.js
package-lock.json
package.json
src/App.js
src/AppEntry.js
src/Components/AffectedClustersTable/AffectedClustersTable.js
src/Components/Breadcrumbs/Breadcrumbs.cy.js
src/Components/Breadcrumbs/index.js
src/Components/Cluster/Cluster.cy.js
src/Components/Cluster/Cluster.js
src/Components/Cluster/index.js
src/Components/ClusterHeader/index.js
src/Components/ClusterRules/ClusterRules.cy.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Components/MessageState/EmptyStates.js
src/Components/Recommendation/Recommendation.cy.js
src/Components/Recommendation/Recommendation.js
src/Components/Recommendation/index.js
src/Components/RecsListTable/RecsListTable.cy.js
src/Components/RecsListTable/RecsListTable.js
src/Routes.js

Implements https://issues.redhat.com/browse/OCPADVISOR-63.
This upgrades one of the dependencies react-router-dom to major version 6; makes the library a singletone with chroming; removes deprecated function calls.

chore(OCPADVISOR-63): Upgrade react-router-dom library to version 6

---

package-lock.json
package.json

Fixes https://issues.redhat.com/browse/OCPADVISOR-59.
This should fix the bug when the users navigated to the cluster or recommendation details page for the second and further times and couldn't see data loaded.
[Screencast from 03-08-2023 01:48:38 PM.webm](https://user-images.githubusercontent.com/31385370/223717362-1c77476e-bc54-403e-8416-f02ec337b06d.webm)
Navigate to recommendation/id or cluster/id pages. Go back to the recommendations/clusters list table via breadcrumbs. Go again to any of the details pages. The end page should load fine (whereas for example in production it does not currently).

fix(OCPADVISOR-59): Fix not loading pages

---

cypress/utils/interceptors.js
src/Components/Cluster/Cluster.cy.js
src/Components/UpgradeRisksAlert/UpgradeRisksAlert.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.cy.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.js

Fixes https://issues.redhat.com/browse/OCPADVISOR-71.
When upgrade risks back end endpoint responds with 404:
- show "not available" message instead of the table,
- render alert banner above the tabs.
When upgrade risks back end endpoint responds with 503 and other error codes (different from 404):
- show "something went wrong" message instead of the table,
- do not render alert banner above the tabs.
As it was described in previous upgrade risks PRs, deploy webpack server together with the mock service. Verify the behavior for clusters that will have 404 or other error codes.

fix: Use correct empty state for 404 upgrade risks

---

cypress/fixtures/api/insights-results-aggregator/v1/clusters/41c30565-b4c9-49f2-a4ce-3277ad22b258/upgrade-risks-prediction.json
src/Components/UpgradeRisksTable/AlertsList.js
src/Components/UpgradeRisksTable/ClusterOperatorsList.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.cy.js

Implements https://issues.redhat.com/browse/OCPADVISOR-86.
This makes the upgrade risks table render alerts or operator conditions names in the anchor tag if they have non-null URL provided from the API response.
Run the PR with the mock service. Navigate to https://stage.foo.redhat.com:1337/preview/openshift/insights/advisor/clusters/00000003-eeee-eeee-eeee-000000000001?active_tab=upgrade_risks and check that the risks names are rendered as links (`a` tag).

feat(OCPADVISOR-86): Render risks with links

---

src/Components/UpgradeRisksTable/AlertsList.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.cy.js
src/Components/UpgradeRisksTable/UpgradeRisksTable.js

Implements https://issues.redhat.com/browse/OCPADVISOR-85. 
Mocked at https://www.sketch.com/s/c5c07e06-f4a1-4c64-9cdf-8b12d8ac9ad5/a/3ooJoZz.
If there are no alerts or cluster operators, then render the green check mark with green label showing 0 upgrade risks.

fix(OCPADVISOR-85): Render check icon if no risks

---

config/overrideChrome.js
cypress/fixtures/api/insights-results-aggregator/v1/clusters/41c30565-b4c9-49f2-a4ce-3277ad22b258/upgrade-risks-prediction.json
cypress/support/commands.js
src/Components/Cluster/Cluster.cy.js
src/Components/Cluster/Cluster.js
src/Components/ClusterTabs/ClusterTabs.js
src/Components/UpgradeRisksAlert/UpgradeRisksAlert.js
src/Components/UpgradeRisksTable/AlertsList.js
src/Components/UpgradeRisksTable/ClusterOperatorsList.js
src/Components/UpgradeRisksTracker/UpgradeRisksTracker.js
src/Components/UpgradeRisksTracker/index.js
src/Services/SmartProxy.js

Implements https://issues.redhat.com/browse/OCPADVISOR-73.
Send analytics to segment.io (Pendo) when users click on "Upgrade risks" tab or access the page via the `/clusters/%id?active_tab=upgrade_risks` link. UI must include two parameters to the request: cluster_id of the browsed cluster and whether the upgrade is recommended or not. The latter is obtained from the GET /upgrade-risks-prediction endpoint.
1. Run PR together with mock service https://github.com/RedHatInsights/ocp-advisor-frontend#using-insights-results-aggregator-mock.
2. Navigate to 00000001-624a-49a5-bab8-4fdc5e51a266 or 00000003-eeee-eeee-eeee-000000000001 clusters and click "Upgrade risks" tab.
3. Check the network request is sent to segment.io (called /t) containing correct properties in its body.
4. Access the same …

feat(OCPADVISOR-73): Track clicks on the Upgrade risks tab

---

src/Components/ClusterTabs/ClusterTabs.js

Fixes https://issues.redhat.com/browse/OCPADVISOR-89.
This fixes incorrect active tab handling provided by `active_tab` URL parameter.
1. Deploy with `npm run start:proxy:beta`,
2. Navigate to any cluster (cluster details page), e.g. https://stage.foo.redhat.com:1337/beta/openshift/insights/advisor/clusters/bc960900-da34-11ed-b4ef-5405db17362c (under `insights-qa`),
3. Click on the upgrade risks tab and refresh the page,
4. Check that 1) the refreshed page keeps upgrade risks tab open, 2) URL contains `active_tab=upgrade_risks`,
5. Click on the recommendations page and refresh the page,
6. Check that 1) the refreshed page keeps recommendations tab open, 2) URL contains `active_tab=recommendations`.

fix(OCPADVISOR-89): Fix active tab handling

---

compiled-lang/en.json
cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
cypress/fixtures/api/insights-results-aggregator/v2/rule.json
cypress/utils/globals.js
src/AppConstants.js
src/Components/Labels/CategoryLabel.js
src/Messages.js

Implements https://issues.redhat.com/browse/OCPADVISOR-111.
This adds one new category to the Category filter: users are now able to filter rules by the Best Practice category.
Go to /openshift/insights/advisor/recommendations, check that you are able to filter rules by Best Practice category. Do the same on any cluster details page. There are currently no recommendations that have this category, so you are supposed to see an empty list.
/recommendations:
https://github.com/RedHatInsights/ocp-advisor-frontend/assets/31385370/8d8ef14d-929e-4757-b9f5-bcae73536765
/clusters/%id:
https://github.com/RedHatInsights/ocp-advisor-frontend/assets/31385370/afdec0dd-f42a-4417-819e-c792f0c89ecb

feat(Filtering): Add Best Practice category

---

src/AppConstants.js

[OCPADVISOR-102](https://issues.redhat.com/browse/OCPADVISOR-102)
Open OCP Advisor > Recommendations > Select a recommendation
The version column is now wider.
Thanks to Georgii for the hint in the ticket, was a quick fix.
Before: 
After:

fix(AffectedClustersTable): Version column wider

---

src/Utilities/useFeatureFlag.js

Add a new feature flag to the unleash that will allow us to develop workloads
To test run "npm run start:proxy:beta"
add to the Recstable or other component
const workloadsEnabled = useFeatureFlag(WORKLOADS_ENABLE_FLAG);
console.log(workloadsEnabled, 'FLAG');
Import required functions and stuff
Check that the console log prints TRUE

feat(OCPADVISOR-124): workloads feature flag

---

src/App.scss
src/AppConstants.js
src/Components/HighestSeverityBadge/HighestSeverityBadge.js
src/Components/WorkloadsList/index.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

[OCPADVISOR-126](https://issues.redhat.com/browse/OCPADVISOR-126)
Added a bare table with some mocked data
How to test:
- Make sure workloads feature flag is enabled in Unleash
- Go to Openshift > Advisor and under Clusters you should see Workloads
- Make sure the table renders

feat(OCPADVISOR-126): Workloads list table

---

src/Components/HighestSeverityBadge/HighestSeverityBadge.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Components/WorkloadsListTable/index.js
src/Services/SmartProxy.js

[OCPADVISOR-143](https://issues.redhat.com/browse/OCPADVISOR-143)
How to setup mock api:
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock)
2. `make build` (takes a few minutes for me, coffee time ☕)
2.1. can speed it up with `make build -j 4` to run multiple jobs at once
3. `make run`
4. Test the mocked api `curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo`
5. Run the app `MOCK=true npm run start:proxy:beta`
6. Workloads should load mocked data
~~Severities are missing, so they're still hardcoded.
Highest Severity is set to 5, but such level doesn't exist?~~ Fixed by the backend folks
Workload details route has to be changed, because the api needs both `cluster_uuid` and `namespace_uuid`
~~Update: Waiting …

feat(OCPADVISOR-143): Connect workloads to mocked API

---

src/AppConstants.js
src/Components/Common/Tables.js
src/Components/HighestSeverityBadge/HighestSeverityBadge.js
src/Components/ShieldSet.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Services/Filters.js
src/Utilities/Workloads.js

Working filters for the workloads table
No URL PARAMS YET! Gonna work on them in a separate PR
How to setup mock api:
Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock)
make build (takes a few minutes for me, coffee time ☕)
2.1. can speed it up with make build -j 4 to run multiple jobs at once
make run
Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
Run the app MOCK=true npm run start:proxy:beta
Workloads should load mocked data
How to test with local data:
You can use the mock data provided from the json file - for that you need comment out data from props and use json

feat(ocpadvisor-123): functional filters with mockdata

---

src/Components/WorkloadsListTable/WorkloadsListTable.js

https://issues.redhat.com/browse/OCPADVISOR-146
Adds pagination to the workloads table
How to setup mock api:
Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock)
make build (takes a few minutes for me, coffee time ☕)
2.1. can speed it up with make build -j 4 to run multiple jobs at once
make run
Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
Run the app MOCK=true npm run start:proxy:beta
Workloads should load mocked data

feat(OCPADVISOR-146): pagination for workloads table

---

src/Components/WorkloadsListTable/WorkloadsListTable.js

We have to subscribe to data in useEffect, so the table would show data on the initial load.

fix(OCPADVISOR-121): hotfix for workloads table

---

src/Components/MessageState/EmptyStates.js
src/Components/WorkloadsListTable/WorkloadsListTable.cy.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

[OCPADVISOR-138](https://issues.redhat.com/browse/OCPADVISOR-138)
When you recieve an empty array of workloads
[Mock](https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/ZVg3O2J)
in `src/Components/WorkloadsListTable/index.js`
replace query with
```js
const query = {
data: { workloads: [] },
isSuccess: true,
isError: false,
};
```
When request returns 404
[Mock](https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/zyQgxvy)
in `src/Components/WorkloadsListTable/index.js`
replace query with
```js
const query = {
data: { workloads: [] },
isSuccess: false,
isError: true,
error: { status: 404 },
};
```

feat(OCPADVISOR-138): workloads table empty state

---

src/Components/WorkloadRules/WorkloadRules.js

The recommendations number on the right side of the toolbar should represent the number of rows that are filtered and shown in the table. Previously it was showing just the number of rows received from the API
[Screencast from 2024-01-05 11-57-01.webm](https://github.com/RedHatInsights/ocp-advisor-frontend/assets/62722417/e95be58d-754a-4017-bc1b-f8c18539100a)

fix(RHINENG-5533): small fix about filtered values rows number

---

src/Components/WorkloadRules/WorkloadRules.js
src/Components/WorkloadRules/WorkloadsRules.test.js
src/Utilities/Workloads.js

Jira link: https://issues.redhat.com/browse/RHINENG-5520
This PR covers sorting for the Description, Objects, and Modified columns. It doesn't cover the total risk column sorting because data is not available in the API yet.
When the first row is expanded and you click on the sort arrow it won't work. It is expected. This is gonna be fixed in a separate PR and covered by a separate Jira card.
How to check the PR 
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock) or pull the latest changes
2. make build
3. can speed it up with make build -j 4 to run multiple jobs at once
4. make run
5. Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
6. Run the app MOCK=true npm run start:proxy:beta
7. …

feat(RHINENG-5520): Workloads details sorting

---

src/Components/MessageState/EmptyStates.js
src/Components/WorkloadRules/WorkloadRules.js

https://issues.redhat.com/browse/RHINENG-5519
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/9lZVpvn
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/P1Wm4yQ
How to run it locally:
Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock) or pull the latest changes
make build
can speed it up with make build -j 4 to run multiple jobs at once
make run
Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
Run the app MOCK=true npm run start:proxy:beta
Workloads should load mocked data
Review the PR

feat(rhineng-5519): empty states for workloads details

---

src/AppConstants.js
src/Components/Common/Tables.js
src/Components/WorkloadRules/WorkloadRules.js
src/Components/WorkloadRules/WorkloadsRules.test.js
src/Services/Filters.js
src/Utilities/Workloads.js

This PR is dependent on the https://github.com/RedHatInsights/ocp-advisor-frontend/pull/653
otherwise, it's hard to make URL params work for the sorting :) 
TOTAL RISK is not present in the API yet, so filtering and sorting by this parameter won't work
There is an issue that for some reason I get offset applied to the URL so I have to fix that as well
How to check the PR
Check that filters and sorting are correctly added to the URL params.
How to run it locally:
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock) or pull the latest changes
2. make build
3. can speed it up with make build -j 4 to run multiple jobs at once
4. make run
5. Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
6. …

feat(RHINENG-6801): Workloads rules url params & filters

---

src/Components/Breadcrumbs/Breadcrumbs.cy.js
src/Components/Breadcrumbs/index.js
src/Components/Workload/Workload.js

Breadcrumbs fix, because of the Double name for the workloads that contain BOTH cluster ID and Namespace ID - breadcrumbs component had to adjusted.
I wrote tests to check that it is fixed
https://issues.redhat.com/browse/RHINENG-5493

fix(rhineng-5493): breadcrumbs fix

---

src/Components/MessageState/EmptyStates.js
src/Components/WorkloadsListTable/WorkloadsListTable.js

New empty state (I don't have mocks for it ready but we discussed it with Shanya personally)
Should appear in case when there are no search results

Fix workloads table empty state

---

src/Services/Filters.js

remove default sorting for workloads rules
1. Clone [insights-results-aggregator-mock](https://github.com/RedHatInsights/insights-results-aggregator-mock) or pull the latest changes
2. make build
3. can speed it up with make build -j 4 to run multiple jobs at once
4. make run
5. Test the mocked api curl localhost:8080/api/insights-results-aggregator/v2/namespaces/dvo
6. Run the app MOCK=true npm run start:proxy:beta
7. Workloads should load mocked data
8. Review the PR

fix(workloads rules): remove default sorting for workloads rules

---

src/Components/ObjectsModal/ObjectsModal.js
src/Components/ObjectsModalTable/ObjectsModalTable.js

fix(workloads): fixing scrollbar and close button overlap

---

src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js

Without using stack item the "View all objects" button was clickable on the whole width of the row.
How to test:
remove stack item and you will be able to click view all object button anywhere in the row

fix(workloads): add stack item to the button

---

src/Components/WorkloadRules/WorkloadRules.js
src/Components/WorkloadRules/WorkloadRules.scss

[Jira ticket](https://issues.redhat.com/browse/RHINENG-7865)
Before
After

fix(RHINENG-7865): Workloads detail expanded recommendation icon has gap

---

src/Components/Common/Tables.js
src/Components/WorkloadRules/WorkloadRules.js
src/Components/WorkloadRules/WorkloadsRules.test.js
src/Utilities/Workloads.js

I had to rethink how I map filters for the workload details.
I made a function using lodash methods to omit any empty filters and create a new object named cleanedUpFilters
After it is created we can check if we have matching recommendations based on the new object pairs of filterKey and filterValue.
I added basic tests to check that it works as expected.
Also, I moved this function to the Workloads utils file

fix(rhineng-7889): fixed a filter bug and wrote more tests

---

src/Components/ObjectsModalTable/ObjectsModalTable.js

Table should be compact 
sketch 
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/dgb4Lp2

fix(rhineng-8046): objects modal compact table

---

src/Components/ShieldSet.js
src/Components/WorkloadsListTable/WorkloadsListTable.js
src/Utilities/Workloads.js

Severity links now lead to the workload details with the applied filter.
Critical severity equals to critical filter applied and same for the rest of severities

feat(rhineng-7974): severity link with path and filters

---

src/Routes.js
src/Utilities/useFeatureFlag.js

To make a production preview release possible I need to add a beta check for the workload routes. That would allow us to turn the feature flag in production ON and serve workloads only in the production preview
I already prepared a PR for the chrome navigation https://github.com/RedHatInsights/chrome-service-backend/pull/403
beta off
beta on

feat(RHINENG-7886): add a beta check for the prod preview release

---

package.json

This should silence the semantic-release bot so that it doesn't add any released labels or comments to PRs which are misleading.
Docs: https://github.com/semantic-release/github, https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugin-options-configuration.

chore: Disable semantic-release comments and labels

---

src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js

Mocks:
https://www.sketch.com/s/46f6d8e3-a4d0-4249-9d57-e6a79b518a6d/a/j4Pa8La
Added a check to render Additional info only in case when more info is present
restructured Steps to the Resolve section. The table was outside the "card" component. So I made it one card component and one Stack Item so it wouldn't have issues with margins
Before
After
I added codeblock component from Alex PR to this PR, its faster that way and we won't have to solve conflicts

fix(RHINENG-5526): More conditional rendering for expanded details and fixing component structure

---

src/Routes.js

The chrome navigation is updated, so we don't need to use the beta flag to hide the navigation.
https://github.com/RedHatInsights/chrome-service-backend/pull/413

removing beta check so we can test it in stage stable

---

src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js

Note: 
should be inside the text message and not separate
like on mocks

fix(rhineng-5526): moving note text into header to align with mocks

---

src/Components/Workload/Workload.cy.js
src/Components/Workload/Workload.js
src/Components/WorkloadHeader/WorkloadHeader.js

Fixing the case when Title and breadcrumbs weren't filled
Wrote a fix and tests
Before fix

fix(RHINENG-9193): breadcrumbs and title when names are absent

---

config/overrideChrome.js
cypress/fixtures/api/insights-results-aggregator/v2/upgrade-risks-prediction.json
cypress/utils/interceptors.js
package-lock.json
package.json
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Services/SmartProxy.js

[RHINENG-8253](https://issues.redhat.com/browse/RHINENG-8253)
There was a miscommunication when the `Update risk` label should be displayed
When the `upgrade-risks-prediction` endpoint returns a prediction where `"upgrade_recommended": false`, then we display the `Update risk` label for that cluster.
How to test:
1. Run the app in prod beta `npm run start`, select prod, then beta
2. Go to Clusters
3. There should be a system which has the label
4. Verify it's the correct system by checking the endpoint

fix(RHINENG-8253): Update risk label condition

---

cypress/utils/interceptors.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js

I wasn't aware this feature is behind a flag so adding it.
Includes a test that checks for labels and api requests if the feature is disabled.
How to test:
1. Run the app in `stage stable` with the flag `ocp-advisor.upgrade-risks.enable-in-stable` disabled in Unleash
2. Go to Clusters
3. Check that you don't see any labels with `Update risk` next to the Cluster name and that there's **no** api requests on `update-risks-prediction` endpoint
4. Enable the flag and check if you can see some clusters with the label, if not check the network tab if there's a request on the `update-risks-prediction` endpoint
5. If you don't have any `Update risk` labels, try the `prod-beta` environment, there might be some there

fix(RHINENG-8253): Update risk label feature flag

---

cypress/utils/interceptors.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Utilities/useFeatureFlag.js

There's a request for a second feature flag until the backend is sorted out.
The new feature flag is `ocp-advisor-ui-upgrade-risks`.
Should show the label only if it's enabled. To enable this feature both upgrade risks feature flags have to be enabled or in case of `preview/beta` env only this flag has to be enabled.

fix: Update risk label second feature flag

---

package-lock.json
src/Components/RecsListTable/RecsListTable.cy.js
src/Components/RecsListTable/RecsListTable.js

Fixes https://issues.redhat.com/browse/RHINENG-8615.
This replaces the deprecated "showViewAffected" flag and passes "ViewAffectedLink" node instead. This fixes the link missing in the expanded rule details.
Go to /openshift/insights/recommendations, makes sure you can see "View affected clusters" in the expanded details for impacting recommendations. The link must not appear for non-impacting rules.

fix(RHINENG-8615): Fix "View ${n} affected clusters" link missing

---

cypress/utils/interceptors.js
src/Components/ClustersListTable/ClustersListTable.cy.js
src/Components/ClustersListTable/ClustersListTable.js
src/Utilities/useFeatureFlag.js

According to [this](https://redhat-internal.slack.com/archives/CLABA9CHY/p1714653331074799?thread_ts=1714482718.650039&cid=CLABA9CHY), the issue was fixed and we're free to remove the feature flag.
How to test:
1. **Enable** the `ocp-advisor-ui-upgrade-risks` ff on unleash stage.
2. Go to Cluster list page
3. Make sure the `/upgrade-risks-prediction` endpoint is called
4. **Disable** the `ocp-advisor-ui-upgrade-risks` ff on unleash stage
5. Go to Cluster list page
6. Make sure the `/upgrade-risks-prediction` endpoint is still called
After the PR is approved, I'll remove the flag on unleash stage. After release it will be removed on prod.

fix(NoTicket): remove second update risk ff

---

src/Components/Modals/DisableRule.cy.js
src/Components/Modals/DisableRule.js

The modal to disable clusters was not waiting for an async operation to complete. Thus, follow up actions (getting the fresh data from backend) were triggered before all changes were submitted. As such,the view was not consistent.
Test for this have been added.
Fixes [RHINENG-10897](https://issues.redhat.com/browse/RHINENG-10897)
The test added here require a revisit, as the implementation is not the best one.
I have tried something more elaborated, but did not work as expected. Advice will be appreciated.
```
describe.only('call order checking', () => {
it('single host', () => {
let number_of_calls = 0;
let calls_so_far = 0;
cy.mount(
<MemoryRouter>
<Intl>
<Provider store={getStore()}>
<DisableRule
isModalOpen={true}
rule={{ rule_id: 'foo|BAR', disabled: false }} …
```

Fix missing await and add tests

---

cypress/fixtures/api/insights-results-aggregator/objectsWithNames.json
src/AppConstants.js
src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
src/Components/ObjectsModal/ObjectsModal.cy.js
src/Components/ObjectsModal/ObjectsModal.js
src/Components/ObjectsModalTable/ObjectsModalTable.js
src/Services/Filters.js
src/Utilities/Workloads.js

https://issues.redhat.com/browse/RHINENG-8850
You can test both versions of the table by changing objectsWithNames value from true to false.
New version of the table

feat(RHINENG-8850): add objects name to the modal
